FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.16.1 --activate

RUN pnpm config set store-dir /app/.pnpm-store --global

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev", "-H", "0.0.0.0"]